/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(add.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e9dd6eda56da0702dcacc5c07a287c1e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/matx/add.h>
// pydoc.h is automatically generated in the build directory
#include <add_pydoc.h>

void bind_add(py::module& m)
{

    using add    = ::gr::matx::add;


    py::class_<add, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<add>>(m, "add", D(add))

        .def(py::init(&add::make),
           D(add,make)
        )
        



        ;




}








